// Converts all generated_puzzles_*.json files into hardcoded_data.dart.
// Run: node to_dart.js
// Output: ../lib/features/game/data/hardcoded_data.dart

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const CATEGORIES = ['Sports', 'Entertainment', 'Pop Culture', 'Social Media'];
const OUT_PATH = path.join(__dirname, '../lib/features/game/data/hardcoded_data.dart');

function deriveDocId(prompt) {
  return crypto
    .createHash('sha256')
    .update(prompt.trim().toLowerCase())
    .digest('hex')
    .substring(0, 24);
}

function escapeDart(str) {
  return str.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function loadCategory(category) {
  const fileName = `generated_puzzles_${category.toLowerCase().replace(/ /g, '_')}.json`;
  const filePath = path.join(__dirname, fileName);
  if (!fs.existsSync(filePath)) {
    console.warn(`  [WARN] No file for ${category} — skipping`);
    return [];
  }
  const raw = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  const puzzles = Array.isArray(raw) ? raw : (raw.puzzles || []);
  const valid = puzzles.filter(p =>
    p.prompt && Array.isArray(p.items) && p.items.length === 5
  );
  console.log(`  ${category}: ${valid.length} questions`);
  return valid;
}

const allPuzzles = [];
const seenIds = new Set();

console.log('\nLoading generated puzzle files...');
for (const cat of CATEGORIES) {
  const puzzles = loadCategory(cat);
  for (const p of puzzles) {
    const id = deriveDocId(p.prompt);
    if (seenIds.has(id)) continue; // cross-category dedup
    seenIds.add(id);
    allPuzzles.push({ ...p, id });
  }
}

console.log(`\nTotal: ${allPuzzles.length} unique questions across ${CATEGORIES.length} categories`);

// Build Dart source
const questionEntries = allPuzzles.map(p => {
  const items = p.items.map(item => `'${escapeDart(item)}'`).join(', ');
  return `  Question(
    id: '${p.id}',
    prompt: '${escapeDart(p.prompt)}',
    items: [${items}],
    category: '${escapeDart(p.category)}',
  )`;
}).join(',\n');

const dart = `import 'question_model.dart';

// Auto-generated by scripts/to_dart.js — do not edit manually.
// Source of truth moves to Firestore once Firebase is set up.
// Re-generate: cd scripts && node generate_puzzles.js ALL && node to_dart.js

final List<Question> hardcodedQuestions = [
${questionEntries},
];
`;

fs.writeFileSync(OUT_PATH, dart, 'utf8');
console.log(`\nWrote ${allPuzzles.length} questions to:\n  ${OUT_PATH}\n`);
